export const GAME_TYPE_ONE = "1";
export const GAME_TYPE_TWO = "2";
export const GAME_TYPE_THREE = "3";
export const FPS = 60;
export const FRAME_RATE = 1000 / FPS;
export const DOWN = 's';
export const UP = 'w';
export const LEFT = 'a';
export const RIGHT = 'd';
export const PADDLE_SPEED = 0.0166; // crossing board in 1 sec